### PR TITLE
chore: update fathom-client

### PR DESCRIPTION
**Pull request by pbortnick**
🎟️ [Asana Task]()

---

## Description

Update `fathom-client` dependency to use new features. Current implementations should still work.

> Note: As of Oct 25, 2023, we no longer support trackGoal for new goals/events. If you’re using trackGoal currently, it’ll continue to work, but the new way of doing events is below.

See [this doc](https://usefathom.com/docs/features/events) for more information.

## PR Checklist 🚀

- [ ] Conduct thorough self-review.
- [ ] Add or update tests as appropriate.
- [ ] Write a useful description (above) to give reviewers appropriate context.
- [ ] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

### CODE REVIEW

**Comment by EnMod** [comment]
LGTM, but I'm thinking it might be worth making a canary release and testing in, say, `www`, just in case 🤔

**Comment by EnMod** [comment]
LGTM, but I'm thinking it might be worth making a canary release and testing in one of our other repos, just in case 🤔

**Comment by pbortnick** [comment]
> LGTM, but I'm thinking it might be worth making a canary release and testing in one of our other repos, just in case 🤔

@EnMod 🧠 smart! I will do that and report back

**Review by EnMod — APPROVED** [review]
@pbortnick Approved pending positive results from trying out the canary!

**Comment by dstaley** [comment]
@pbortnick since this is an update to a version that's still within the semver range for the existing package, we don't need to publish this as an update to the `platform-analytics` package. You can run `npm update fathom-client` to get the latest v3.6.0 version within the monorepo.

**Pull request closed without merging**
